### PR TITLE
fixed crash when user cancels new map creation

### PR DESCRIPTION
**Pull request by dimetcm**

### CODE REVIEW

**Review by BobbyAnguelov — APPROVED** [review]
Will add this to the mainline!

**Review by BobbyAnguelov — COMMENTED** [review]
This function basically "serializes" a map. While it's not expected for someone to do this with a transient map, I don't feel it should be explicitly prevented.

Loading also has no relevance for this function since I don't care about the actual runtime state of anything but rather only the data that needs to be serialized, hence the check that there are no add/remove operations pending that would change the state.

**Review by BobbyAnguelov — COMMENTED** [review]
This code is unfortunately kinda in a half-built/half broken state. 

I started an overhaul for the resource browser but work and some medical stuff got in the way. This code will change significantly soon (ish) as I also want to provide some automatic reference removal/updating for move/rename/delete operations.

**Comment by BobbyAnguelov** [comment]
Thanks for the PR, I've integrated the crash fix into the mainline (github is just a manual mirror). 

There's been limited progress on a bunch of stuff as we are in the middle of a complete rendering infrastructure overhaul so unfortunately a bunch of stuff is in a bad state atm as what free time I've had has mostly gone into supporting that part.

If you find any more issue, feel free to flag them and I'll cherry pick what makes sense into our mainline.

**Comment by dimetcm** [comment]
> This function basically "serializes" a map. While it's not expected for someone to do this with a transient map, I don't feel it should be explicitly prevented.
> 
> Loading also has no relevance for this function since I don't care about the actual runtime state of anything but rather only the data that needs to be serialized, hence the check that there are no add/remove operations pending that would change the state.

I'm hitting that assert when creating a new map, `EntityMapEditor::CreateNewMap`. As I understood dummy transient map is serialized first and it asserts since the `map.status == unloaded`. If loading has no relevance would you recommend simply removing that assert?

**Comment by dimetcm** [comment]
> Thanks for the PR, I've integrated the crash fix into the mainline (github is just a manual mirror).
> 
> There's been limited progress on a bunch of stuff as we are in the middle of a complete rendering infrastructure overhaul so unfortunately a bunch of stuff is in a bad state atm as what free time I've had has mostly gone into supporting that part.
> 
> If you find any more issue, feel free to flag them and I'll cherry pick what makes sense into our mainline.

Huge thanks for sharing the engine, Bobby! It's truly amazing work.

**Comment by BobbyAnguelov** [comment]
Oh that's a different and real issue. I'll try to provide a real solution for this fuckup tonight. Thanks for pointing it out.

**Pull request closed without merging**
